{
  config,
  inputs,
  pkgs,
  lib,
  ...
}:
{
  environment.systemPackages = [
    pkgs.ghostty
    pkgs.kitty
    inputs.zen-browser.packages.x86_64-linux.default
    inputs.agenix.packages.x86_64-linux.default
    inputs.trigo.packages.x86_64-linux.default
    inputs.aphelion.packages.x86_64-linux.default
    inputs.llm.packages.x86_64-linux.opencode
    inputs.llm.packages.x86_64-linux.pi
    inputs.llm.packages.x86_64-linux.crush
    inputs.wallpapers.packages.x86_64-linux.default
    inputs.helium.defaultPackage.x86_64-linux
    inputs.noctalia.packages.x86_64-linux.default
  ];
}
