{
  lib,
  pkgs,
  config,
  ...
}:
let
  generator = pkgs.writeShellApplication {
    name = "generate-vesktop-theme";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      colors="$HOME/.config/noctalia/colors.json"
      out="$HOME/.config/vesktop/themes/system24-kanagawa.theme.css"
      quickcss="$HOME/.config/vesktop/settings/quickCss.css"

      [ -f "$colors" ] || exit 0

      surface=$(jq -r '.mSurface' "$colors")
      surface_variant=$(jq -r '.mSurfaceVariant' "$colors")
      on_surface=$(jq -r '.mOnSurface' "$colors")
      on_surface_variant=$(jq -r '.mOnSurfaceVariant' "$colors")
      outline=$(jq -r '.mOutline' "$colors")
      primary=$(jq -r '.mPrimary' "$colors")
      secondary=$(jq -r '.mSecondary' "$colors")
      tertiary=$(jq -r '.mTertiary' "$colors")
      error=$(jq -r '.mError' "$colors")

      mkdir -p "$(dirname "$out")" "$(dirname "$quickcss")"

      generate_theme_css() {
      cat << EOF
/**
 * @name system24 (kanagawa)
 * @description system24 with wallpaper-matched matugen colors, generated by noctalia
 * @version 1.0.0
 */

@import url('https://refact0r.github.io/system24/build/system24.css');

body {
    --font: 'Maple Mono NF';
    --code-font: 'Maple Mono NF';
    font-weight: 300;
    letter-spacing: -0.05ch;
    --gap: 12px;
    --divider-thickness: 4px;
    --border-thickness: 2px;
    --border-hover-transition: 0.2s ease;
    --animations: on;
    --list-item-transition: 0.2s ease;
    --dms-icon-svg-transition: 0.4s ease;
    --top-bar-height: var(--gap);
    --top-bar-button-position: titlebar;
    --top-bar-title-position: off;
    --subtle-top-bar-title: off;
    --custom-window-controls: off;
    --window-control-size: 14px;
    --custom-dms-icon: off;
    --dms-icon-svg-url: url('''');
    --dms-icon-svg-size: 90%;
    --dms-icon-color-before: var(--icon-subtle);
    --dms-icon-color-after: var(--white);
    --custom-dms-background: off;
    --background-image: off;
    --transparency-tweaks: off;
    --remove-bg-layer: off;
    --panel-blur: off;
    --blur-amount: 12px;
    --bg-floating: var(--bg-3);
    --small-user-panel: on;
    --unrounding: on;
    --custom-spotify-bar: on;
    --ascii-titles: on;
    --ascii-loader: system24;
    --panel-labels: on;
    --label-color: var(--text-muted);
    --label-font-weight: 500;
}

$(generate_colors_css)
EOF
      }

      generate_colors_css() {
      cat << EOF
:root {
    --colors: on;

    --text-0: $surface;
    --text-1: color-mix(in oklch, $on_surface, white 20%);
    --text-2: $on_surface;
    --text-3: color-mix(in oklch, $on_surface, $surface 15%);
    --text-4: $on_surface_variant;
    --text-5: $outline;

    --bg-1: color-mix(in oklch, $surface_variant, $on_surface 20%);
    --bg-2: color-mix(in oklch, $surface, $surface_variant 50%);
    --bg-3: $surface_variant;
    --bg-4: $surface;
    --hover: color-mix(in srgb, $on_surface_variant, transparent 87%);
    --active: color-mix(in srgb, $on_surface_variant, transparent 73%);
    --active-2: color-mix(in srgb, $on_surface_variant, transparent 66%);
    --message-hover: color-mix(in srgb, $on_surface, transparent 90%);

    --accent-1: var(--blue-1);
    --accent-2: var(--blue-2);
    --accent-3: var(--blue-3);
    --accent-4: var(--blue-4);
    --accent-5: var(--blue-5);
    --accent-new: var(--red-2);
    --mention: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 90%) 40%, transparent);
    --mention-hover: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 95%) 40%, transparent);
    --reply: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 90%) 40%, transparent);
    --reply-hover: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 95%) 40%, transparent);

    --online: var(--green-2);
    --dnd: var(--red-2);
    --idle: var(--yellow-2);
    --streaming: var(--purple-2);
    --offline: var(--text-4);

    --border-light: var(--hover);
    --border: var(--active);
    --border-hover: var(--accent-2);
    --button-border: color-mix(in srgb, $on_surface, transparent 90%);

    --red-1: color-mix(in oklch, $error, white 15%);
    --red-2: $error;
    --red-3: $error;
    --red-4: color-mix(in oklch, $error, black 10%);
    --red-5: color-mix(in oklch, $error, black 20%);

    --green-1: oklch(from $tertiary min(calc(l + 0.08), 0.92) 0.14 145);
    --green-2: oklch(from $tertiary l 0.15 145);
    --green-3: oklch(from $tertiary l 0.15 145);
    --green-4: oklch(from $tertiary max(calc(l - 0.06), 0.05) 0.13 145);
    --green-5: oklch(from $tertiary max(calc(l - 0.12), 0.05) 0.12 145);

    --blue-1: color-mix(in oklch, $primary, white 15%);
    --blue-2: $primary;
    --blue-3: $primary;
    --blue-4: color-mix(in oklch, $primary, black 10%);
    --blue-5: color-mix(in oklch, $primary, black 20%);

    --yellow-1: oklch(from $secondary min(calc(l + 0.08), 0.92) 0.14 95);
    --yellow-2: oklch(from $secondary l 0.15 95);
    --yellow-3: oklch(from $secondary l 0.15 95);
    --yellow-4: oklch(from $secondary max(calc(l - 0.06), 0.05) 0.13 95);
    --yellow-5: oklch(from $secondary max(calc(l - 0.12), 0.05) 0.12 95);

    --purple-1: color-mix(in oklch, $on_surface_variant, white 15%);
    --purple-2: $on_surface_variant;
    --purple-3: $on_surface_variant;
    --purple-4: color-mix(in oklch, $on_surface_variant, black 10%);
    --purple-5: color-mix(in oklch, $on_surface_variant, black 20%);
}
EOF
      }

      generate_theme_css > "$out"
      generate_colors_css > "$quickcss"
    '';
  };
in
{
  options.bars.noctalia.themes.vesktop.enable = lib.mkEnableOption "vesktop noctalia theme" // {
    default = true;
  };

  config = lib.mkIf (config.bars.noctalia.enable && config.bars.noctalia.themes.vesktop.enable) {
    bars.noctalia.themeGenerators = [ generator ];

    home.activation.seedVesktopTheme = lib.hm.dag.entryAfter [ "unlockNoctaliaColors" ] ''
      ${generator}/bin/generate-vesktop-theme || true
    '';
  };
}
