{
  lib,
  pkgs,
  osConfig,
  config,
  inputs,
  ...
}:
let
  t = osConfig.host.themeData.base16Scheme;
  defaultNoctaliaColors = pkgs.writeText "noctalia-colors-default.json" (builtins.toJSON {
    mError = "#${t.base08}";
    mHover = "#${t.base0C}";
    mOnError = "#${t.base00}";
    mOnHover = "#${t.base00}";
    mOnPrimary = "#${t.base00}";
    mOnSecondary = "#${t.base00}";
    mOnSurface = "#${t.base05}";
    mOnSurfaceVariant = "#${t.base04}";
    mOnTertiary = "#${t.base00}";
    mOutline = "#${t.base03}";
    mPrimary = "#${t.base0D}";
    mSecondary = "#${t.base0E}";
    mShadow = "#${t.base00}";
    mSurface = "#${t.base00}";
    mSurfaceVariant = "#${t.base01}";
    mTertiary = "#${t.base0C}";
  });

  generateVesktopTheme = pkgs.writeShellApplication {
    name = "generate-vesktop-theme";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      colors="$HOME/.config/noctalia/colors.json"
      out="$HOME/.config/vesktop/themes/system24-kanagawa.theme.css"

      [ -f "$colors" ] || exit 0

      surface=$(jq -r '.mSurface' "$colors")
      surface_variant=$(jq -r '.mSurfaceVariant' "$colors")
      on_surface=$(jq -r '.mOnSurface' "$colors")
      on_surface_variant=$(jq -r '.mOnSurfaceVariant' "$colors")
      outline=$(jq -r '.mOutline' "$colors")
      primary=$(jq -r '.mPrimary' "$colors")
      secondary=$(jq -r '.mSecondary' "$colors")
      tertiary=$(jq -r '.mTertiary' "$colors")
      error=$(jq -r '.mError' "$colors")

      mkdir -p "$(dirname "$out")"

      cat > "$out" << EOF
/**
 * @name system24 (kanagawa)
 * @description system24 with wallpaper-matched matugen colors, generated by noctalia
 * @version 1.0.0
 */

@import url('https://refact0r.github.io/system24/build/system24.css');

body {
    --font: 'Maple Mono NF';
    --code-font: 'Maple Mono NF';
    font-weight: 300;
    letter-spacing: -0.05ch;
    --gap: 12px;
    --divider-thickness: 4px;
    --border-thickness: 2px;
    --border-hover-transition: 0.2s ease;
    --animations: on;
    --list-item-transition: 0.2s ease;
    --dms-icon-svg-transition: 0.4s ease;
    --top-bar-height: var(--gap);
    --top-bar-button-position: titlebar;
    --top-bar-title-position: off;
    --subtle-top-bar-title: off;
    --custom-window-controls: off;
    --window-control-size: 14px;
    --custom-dms-icon: off;
    --dms-icon-svg-url: url('''');
    --dms-icon-svg-size: 90%;
    --dms-icon-color-before: var(--icon-subtle);
    --dms-icon-color-after: var(--white);
    --custom-dms-background: off;
    --background-image: off;
    --transparency-tweaks: off;
    --remove-bg-layer: off;
    --panel-blur: off;
    --blur-amount: 12px;
    --bg-floating: var(--bg-3);
    --small-user-panel: on;
    --unrounding: on;
    --custom-spotify-bar: on;
    --ascii-titles: on;
    --ascii-loader: system24;
    --panel-labels: on;
    --label-color: var(--text-muted);
    --label-font-weight: 500;
}

:root {
    --colors: on;

    --text-0: $surface;
    --text-1: color-mix(in oklch, $on_surface, white 20%);
    --text-2: $on_surface;
    --text-3: color-mix(in oklch, $on_surface, $surface 15%);
    --text-4: $on_surface_variant;
    --text-5: $outline;

    --bg-1: color-mix(in oklch, $surface_variant, $on_surface 20%);
    --bg-2: color-mix(in oklch, $surface, $surface_variant 50%);
    --bg-3: $surface_variant;
    --bg-4: $surface;
    --hover: color-mix(in srgb, $on_surface_variant, transparent 87%);
    --active: color-mix(in srgb, $on_surface_variant, transparent 73%);
    --active-2: color-mix(in srgb, $on_surface_variant, transparent 66%);
    --message-hover: color-mix(in srgb, $on_surface, transparent 90%);

    --accent-1: var(--blue-1);
    --accent-2: var(--blue-2);
    --accent-3: var(--blue-3);
    --accent-4: var(--blue-4);
    --accent-5: var(--blue-5);
    --accent-new: var(--red-2);
    --mention: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 90%) 40%, transparent);
    --mention-hover: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 95%) 40%, transparent);
    --reply: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 90%) 40%, transparent);
    --reply-hover: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 95%) 40%, transparent);

    --online: var(--green-2);
    --dnd: var(--red-2);
    --idle: var(--yellow-2);
    --streaming: var(--purple-2);
    --offline: var(--text-4);

    --border-light: var(--hover);
    --border: var(--active);
    --border-hover: var(--accent-2);
    --button-border: color-mix(in srgb, $on_surface, transparent 90%);

    --red-1: color-mix(in oklch, $error, white 15%);
    --red-2: $error;
    --red-3: $error;
    --red-4: color-mix(in oklch, $error, black 10%);
    --red-5: color-mix(in oklch, $error, black 20%);

    --green-1: color-mix(in oklch, $tertiary, white 15%);
    --green-2: $tertiary;
    --green-3: $tertiary;
    --green-4: color-mix(in oklch, $tertiary, black 10%);
    --green-5: color-mix(in oklch, $tertiary, black 20%);

    --blue-1: color-mix(in oklch, $primary, white 15%);
    --blue-2: $primary;
    --blue-3: $primary;
    --blue-4: color-mix(in oklch, $primary, black 10%);
    --blue-5: color-mix(in oklch, $primary, black 20%);

    --yellow-1: color-mix(in oklch, $secondary, white 15%);
    --yellow-2: $secondary;
    --yellow-3: $secondary;
    --yellow-4: color-mix(in oklch, $secondary, black 10%);
    --yellow-5: color-mix(in oklch, $secondary, black 20%);

    --purple-1: color-mix(in oklch, $on_surface_variant, white 15%);
    --purple-2: $on_surface_variant;
    --purple-3: $on_surface_variant;
    --purple-4: color-mix(in oklch, $on_surface_variant, black 10%);
    --purple-5: color-mix(in oklch, $on_surface_variant, black 20%);
}
EOF
    '';
  };
in
{
  options = {
    bars.noctalia.enable = lib.mkEnableOption "Enable noctalia bar";
  };
  config = lib.mkIf config.bars.noctalia.enable {
    home.activation.unlockNoctaliaColors = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      colors="$HOME/.config/noctalia/colors.json"
      if [ -L "$colors" ]; then
        tmp=$(${pkgs.coreutils}/bin/mktemp)
        ${pkgs.coreutils}/bin/cp "$(${pkgs.coreutils}/bin/readlink "$colors")" "$tmp"
        ${pkgs.coreutils}/bin/rm "$colors"
        ${pkgs.coreutils}/bin/mv "$tmp" "$colors"
      elif [ ! -f "$colors" ]; then
        ${pkgs.coreutils}/bin/cp ${defaultNoctaliaColors} "$colors"
        ${pkgs.coreutils}/bin/chmod 644 "$colors"
      fi
    '';

    home.activation.seedVesktopTheme = lib.hm.dag.entryAfter [ "unlockNoctaliaColors" ] ''
      ${generateVesktopTheme}/bin/generate-vesktop-theme || true
    '';

    programs.noctalia-shell = {
      enable = lib.mkIf (osConfig.host.bar == "noctalia") true;
      systemd.enable = lib.mkIf (osConfig.host.bar == "noctalia") true;
      settings = {
        appLauncher = {
          autoPasteClipboard = false;
          customLaunchPrefix = ">";
          customLaunchPrefixEnabled = false;
          enableClipPreview = true;
          enableClipboardHistory = true;
          iconMode = "tabler";
          ignoreMouseInput = false;
          position = "center";
          screenshotAnnotationTool = "";
          showCategories = true;
          showIconBackground = true;
          sortByMostUsed = true;
          terminalCommand = "ghostty -e";
          useApp2Unit = false;
          viewMode = "list";
        };
        audio = {
          cavaFrameRate = 30;
          externalMixer = "pwvucontrol || pavucontrol";
          mprisBlacklist = [

          ];
          preferredPlayer = "";
          visualizerType = "linear";
          volumeOverdrive = false;
          volumeStep = 5;
        };
        bar = {
          backgroundOpacity = lib.mkForce 0;
          capsuleOpacity = lib.mkForce 1;
          density = lib.mkForce "comfortable";
          exclusive = lib.mkForce true;
          floating = lib.mkForce true;
          marginHorizontal = lib.mkForce 1;
          marginVertical = lib.mkForce 0.25;
          monitors = [

          ];
          outerCorners = true;
          position = "top";
          showCapsule = true;
          showOutline = true;
          useSeparateOpacity = true;
          widgets = {
            center = [
              {
                characterCount = 2;
                colorizeIcons = false;
                enableScrollWheel = true;
                followFocusedScreen = false;
                groupedBorderOpacity = 1;
                hideUnoccupied = false;
                iconScale = 0.8;
                id = "Workspace";
                labelMode = "index";
                showApplications = false;
                showLabelsOnlyWhenOccupied = true;
                unfocusedIconsOpacity = 1;
              }
            ];
            left = [
              {
                icon = "rocket";
                id = "Launcher";
                usePrimaryColor = false;
              }
              {
                customFont = "";
                formatHorizontal = "HH:mm ddd, MMM dd";
                formatVertical = "HH mm - dd MM";
                id = "Clock";
                tooltipFormat = "HH:mm ddd, MMM dd";
                useCustomFont = false;
                usePrimaryColor = false;
              }
              {
                compactMode = true;
                diskPath = "/";
                id = "SystemMonitor";
                showCpuTemp = true;
                showCpuUsage = true;
                showDiskUsage = false;
                showGpuTemp = false;
                showLoadAverage = false;
                showMemoryAsPercent = false;
                showMemoryUsage = true;
                showNetworkStats = false;
                useMonospaceFont = true;
                usePrimaryColor = false;
              }
              {
                colorizeIcons = false;
                hideMode = "hidden";
                id = "ActiveWindow";
                maxWidth = 145;
                scrollingMode = "hover";
                showIcon = true;
                useFixedWidth = false;
              }
              {
                hideMode = "hidden";
                hideWhenIdle = false;
                id = "MediaMini";
                maxWidth = 145;
                scrollingMode = "hover";
                showAlbumArt = false;
                showArtistFirst = true;
                showProgressRing = true;
                showVisualizer = false;
                useFixedWidth = false;
                visualizerType = "linear";
              }
            ];
            right = [
              {
                id = "ScreenRecorder";
              }
              {
                blacklist = [

                ];
                colorizeIcons = false;
                drawerEnabled = true;
                hidePassive = false;
                id = "Tray";
                pinned = [

                ];
              }
              {
                hideWhenZero = false;
                id = "NotificationHistory";
                showUnreadBadge = true;
              }
              {
                deviceNativePath = "";
                displayMode = "onhover";
                hideIfNotDetected = true;
                id = "Battery";
                showNoctaliaPerformance = false;
                showPowerProfiles = false;
                warningThreshold = 30;
              }
              {
                displayMode = "onhover";
                id = "Volume";
              }
              {
                displayMode = "onhover";
                id = "Brightness";
              }
              {
                colorizeDistroLogo = false;
                colorizeSystemIcon = "none";
                customIconPath = "";
                enableColorization = false;
                icon = "noctalia";
                id = "ControlCenter";
                useDistroLogo = true;
              }
            ];
          };
        };
        brightness = {
          brightnessStep = 5;
          enableDdcSupport = true;
          enforceMinimum = true;
        };
        calendar = {
          cards = [
            {
              enabled = true;
              id = "calendar-header-card";
            }
            {
              enabled = true;
              id = "calendar-month-card";
            }
            {
              enabled = true;
              id = "timer-card";
            }
            {
              enabled = true;
              id = "weather-card";
            }
          ];
        };
        colorSchemes = {
          darkMode = true;
          manualSunrise = "06:30";
          manualSunset = "18:30";
          matugenSchemeType = "scheme-fruit-salad";
          schedulingMode = "off";
          useWallpaperColors = true;
        };
        controlCenter = {
          cards = [
            {
              enabled = true;
              id = "profile-card";
            }
            {
              enabled = true;
              id = "shortcuts-card";
            }
            {
              enabled = true;
              id = "audio-card";
            }
            {
              enabled = false;
              id = "brightness-card";
            }
            {
              enabled = true;
              id = "weather-card";
            }
            {
              enabled = true;
              id = "media-sysmon-card";
            }
          ];
          diskPath = "/";
          position = "close_to_bar_button";
          shortcuts = {
            left = [
              {
                id = "Network";
              }
              {
                id = "Bluetooth";
              }
              {
                id = "ScreenRecorder";
              }
              {
                id = "WallpaperSelector";
              }
            ];
            right = [
              {
                id = "Notifications";
              }
              {
                id = "PowerProfile";
              }
              {
                id = "KeepAwake";
              }
              {
                id = "NightLight";
              }
            ];
          };
        };
        desktopWidgets = {
          enabled = false;
          gridSnap = false;
          monitorWidgets = [

          ];
        };
        dock = {
          enabled = false;
        };
        general = {
          allowPanelsOnScreenWithoutBar = true;
          animationDisabled = false;
          animationSpeed = 1;
          avatarImage = "/home/franky/.face";
          boxRadiusRatio = 1;
          compactLockScreen = false;
          lockScreenAnimations = true;
          enableLockScreenMediaControls = true;
          dimmerOpacity = 0.2;
          enableShadows = true;
          forceBlackScreenCorners = false;
          iRadiusRatio = 1;
          language = "";
          lockOnSuspend = true;
          radiusRatio = 1;
          scaleRatio = 1;
          screenRadiusRatio = 1;
          shadowDirection = "bottom_right";
          shadowOffsetX = 2;
          shadowOffsetY = 3;
          showChangelogOnStartup = true;
          showHibernateOnLockScreen = false;
          showScreenCorners = false;
          showSessionButtonsOnLockScreen = true;
        };
        hooks = {
          darkModeChange = "";
          enabled = true;
          performanceModeDisabled = "";
          performanceModeEnabled = "";
          screenLock = "";
          screenUnlock = "";
          wallpaperChange = "${generateVesktopTheme}/bin/generate-vesktop-theme";
        };
        location = {
          analogClockInCalendar = false;
          firstDayOfWeek = -1;
          hideWeatherCityName = false;
          hideWeatherTimezone = false;
          name = "Madrid";
          showCalendarEvents = true;
          showCalendarWeather = true;
          showWeekNumberInCalendar = false;
          use12hourFormat = false;
          useFahrenheit = false;
          weatherEnabled = true;
          weatherShowEffects = true;
        };
        network = {
          bluetoothDetailsViewMode = "grid";
          bluetoothHideUnnamedDevices = false;
          bluetoothRssiPollIntervalMs = 10000;
          bluetoothRssiPollingEnabled = false;
          wifiDetailsViewMode = "grid";
          wifiEnabled = true;
        };
        nightLight = {
          autoSchedule = true;
          dayTemp = "6500";
          enabled = false;
          forced = false;
          manualSunrise = "06:30";
          manualSunset = "18:30";
          nightTemp = "4000";
        };
        notifications = {
          backgroundOpacity = lib.mkForce 1;
          criticalUrgencyDuration = 15;
          enableKeyboardLayoutToast = true;
          enabled = true;
          location = "top_right";
          lowUrgencyDuration = 3;
          monitors = [

          ];
          normalUrgencyDuration = 8;
          overlayLayer = true;
          respectExpireTimeout = false;
          saveToHistory = {
            critical = true;
            low = true;
            normal = true;
          };
          sounds = {
            criticalSoundFile = "";
            enabled = false;
            excludedApps = "discord,firefox,chrome,chromium,edge";
            lowSoundFile = "";
            normalSoundFile = "";
            separateSounds = false;
            volume = 0.5;
          };
        };
        osd = {
          autoHideMs = 2000;
          backgroundOpacity = lib.mkForce 1;
          enabled = true;
          enabledTypes = [
            0
            1
            2
            4
          ];
          location = "top_right";
          monitors = [

          ];
          overlayLayer = true;
        };
        screenRecorder = {
          audioCodec = "opus";
          audioSource = "default_output";
          colorRange = "limited";
          copyToClipboard = false;
          directory = "/home/franky/Videos";
          frameRate = 60;
          quality = "very_high";
          showCursor = true;
          videoCodec = "h264";
          videoSource = "portal";
        };
        sessionMenu = {
          countdownDuration = 10000;
          enableCountdown = true;
          largeButtonsLayout = "grid";
          largeButtonsStyle = false;
          position = "center";
          powerOptions = [
            {
              action = "lock";
              enabled = true;
            }
            {
              action = "suspend";
              enabled = true;
            }
            {
              action = "hibernate";
              enabled = true;
            }
            {
              action = "reboot";
              enabled = true;
            }
            {
              action = "logout";
              enabled = true;
            }
            {
              action = "shutdown";
              enabled = true;
            }
          ];
          showHeader = true;
          showNumberLabels = true;
        };
        settingsVersion = 37;
        systemMonitor = {
          cpuCriticalThreshold = 90;
          cpuPollingInterval = 3000;
          cpuWarningThreshold = 80;
          criticalColor = "";
          diskCriticalThreshold = 90;
          diskPollingInterval = 3000;
          diskWarningThreshold = 80;
          enableDgpuMonitoring = false;
          externalMonitor = "resources || missioncenter || jdsystemmonitor || corestats || system-monitoring-center || gnome-system-monitor || plasma-systemmonitor || mate-system-monitor || ukui-system-monitor || deepin-system-monitor || pantheon-system-monitor";
          gpuCriticalThreshold = 90;
          gpuPollingInterval = 3000;
          gpuWarningThreshold = 80;
          loadAvgPollingInterval = 3000;
          memCriticalThreshold = 90;
          memPollingInterval = 3000;
          memWarningThreshold = 80;
          networkPollingInterval = 3000;
          tempCriticalThreshold = 90;
          tempPollingInterval = 3000;
          tempWarningThreshold = 80;
          useCustomColors = false;
          warningColor = "";
        };
        templates = {
          alacritty = false;
          cava = false;
          code = false;
          discord = false;
          emacs = false;
          enableUserTemplates = false;
          foot = false;
          fuzzel = false;
          ghostty = true;
          gtk = false;
          helix = false;
          hyprland = false;
          kcolorscheme = false;
          kitty = true;
          mango = false;
          niri = false;
          pywalfox = false;
          qt = false;
          spicetify = false;
          telegram = false;
          vicinae = false;
          walker = false;
          wezterm = false;
          yazi = false;
          zed = false;
          zenBrowser = false;
        };
        ui = {
          bluetoothDetailsViewMode = "grid";
          bluetoothHideUnnamedDevices = false;
          boxBorderEnabled = false;
          fontDefault = lib.mkForce "Maple Mono NF";
          fontDefaultScale = lib.mkForce 1;
          fontFixed = lib.mkForce "monospace";
          fontFixedScale = 1;
          networkPanelView = "wifi";
          panelBackgroundOpacity = lib.mkForce 1;
          panelsAttachedToBar = true;
          settingsPanelMode = "attached";
          tooltipsEnabled = true;
          wifiDetailsViewMode = "grid";
        };
        wallpaper = {
          directory = "${inputs.wallpapers}";
          enableMultiMonitorDirectories = false;
          enabled = true;
          fillColor = "#000000";
          fillMode = "crop";
          hideWallpaperFilenames = false;
          monitorDirectories = [

          ];
          overviewEnabled = false;
          panelPosition = "follow_bar";
          randomEnabled = false;
          randomIntervalSec = 300;
          recursiveSearch = true;
          setWallpaperOnAllMonitors = true;
          solidColor = "#1a1a2e";
          transitionDuration = 1500;
          transitionEdgeSmoothness = 0.05;
          transitionType = "random";
          useSolidColor = false;
          useWallhaven = false;
          wallhavenApiKey = "";
          wallhavenCategories = "111";
          wallhavenOrder = "desc";
          wallhavenPurity = "100";
          wallhavenQuery = "";
          wallhavenRatios = "";
          wallhavenResolutionHeight = "";
          wallhavenResolutionMode = "atleast";
          wallhavenResolutionWidth = "";
          wallhavenSorting = "relevance";
          wallpaperChangeMode = "random";
        };
      };
    };
  };
}
