{
  lib,
  pkgs,
  config,
  osConfig,
  ...
}:
let
  t = osConfig.host.themeData.base16Scheme;

  defaultNoctaliaColors = pkgs.writeText "noctalia-colors-default.json" (builtins.toJSON {
    mError = "#${t.base08}";
    mHover = "#${t.base0C}";
    mOnError = "#${t.base00}";
    mOnHover = "#${t.base00}";
    mOnPrimary = "#${t.base00}";
    mOnSecondary = "#${t.base00}";
    mOnSurface = "#${t.base05}";
    mOnSurfaceVariant = "#${t.base04}";
    mOnTertiary = "#${t.base00}";
    mOutline = "#${t.base03}";
    mPrimary = "#${t.base0D}";
    mSecondary = "#${t.base0E}";
    mShadow = "#${t.base00}";
    mSurface = "#${t.base00}";
    mSurfaceVariant = "#${t.base01}";
    mTertiary = "#${t.base0C}";
  });

  generateVesktopTheme = pkgs.writeShellApplication {
    name = "generate-vesktop-theme";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      colors="$HOME/.config/noctalia/colors.json"
      out="$HOME/.config/vesktop/themes/system24-kanagawa.theme.css"
      quickcss="$HOME/.config/vesktop/settings/quickCss.css"

      [ -f "$colors" ] || exit 0

      surface=$(jq -r '.mSurface' "$colors")
      surface_variant=$(jq -r '.mSurfaceVariant' "$colors")
      on_surface=$(jq -r '.mOnSurface' "$colors")
      on_surface_variant=$(jq -r '.mOnSurfaceVariant' "$colors")
      outline=$(jq -r '.mOutline' "$colors")
      primary=$(jq -r '.mPrimary' "$colors")
      secondary=$(jq -r '.mSecondary' "$colors")
      tertiary=$(jq -r '.mTertiary' "$colors")
      error=$(jq -r '.mError' "$colors")

      mkdir -p "$(dirname "$out")" "$(dirname "$quickcss")"

      generate_theme_css() {
      cat << EOF
/**
 * @name system24 (kanagawa)
 * @description system24 with wallpaper-matched matugen colors, generated by noctalia
 * @version 1.0.0
 */

@import url('https://refact0r.github.io/system24/build/system24.css');

body {
    --font: 'Maple Mono NF';
    --code-font: 'Maple Mono NF';
    font-weight: 300;
    letter-spacing: -0.05ch;
    --gap: 12px;
    --divider-thickness: 4px;
    --border-thickness: 2px;
    --border-hover-transition: 0.2s ease;
    --animations: on;
    --list-item-transition: 0.2s ease;
    --dms-icon-svg-transition: 0.4s ease;
    --top-bar-height: var(--gap);
    --top-bar-button-position: titlebar;
    --top-bar-title-position: off;
    --subtle-top-bar-title: off;
    --custom-window-controls: off;
    --window-control-size: 14px;
    --custom-dms-icon: off;
    --dms-icon-svg-url: url('''');
    --dms-icon-svg-size: 90%;
    --dms-icon-color-before: var(--icon-subtle);
    --dms-icon-color-after: var(--white);
    --custom-dms-background: off;
    --background-image: off;
    --transparency-tweaks: off;
    --remove-bg-layer: off;
    --panel-blur: off;
    --blur-amount: 12px;
    --bg-floating: var(--bg-3);
    --small-user-panel: on;
    --unrounding: on;
    --custom-spotify-bar: on;
    --ascii-titles: on;
    --ascii-loader: system24;
    --panel-labels: on;
    --label-color: var(--text-muted);
    --label-font-weight: 500;
}

$(generate_colors_css)
EOF
      }

      generate_colors_css() {
      cat << EOF
:root {
    --colors: on;

    --text-0: $surface;
    --text-1: color-mix(in oklch, $on_surface, white 20%);
    --text-2: $on_surface;
    --text-3: color-mix(in oklch, $on_surface, $surface 15%);
    --text-4: $on_surface_variant;
    --text-5: $outline;

    --bg-1: color-mix(in oklch, $surface_variant, $on_surface 20%);
    --bg-2: color-mix(in oklch, $surface, $surface_variant 50%);
    --bg-3: $surface_variant;
    --bg-4: $surface;
    --hover: color-mix(in srgb, $on_surface_variant, transparent 87%);
    --active: color-mix(in srgb, $on_surface_variant, transparent 73%);
    --active-2: color-mix(in srgb, $on_surface_variant, transparent 66%);
    --message-hover: color-mix(in srgb, $on_surface, transparent 90%);

    --accent-1: var(--blue-1);
    --accent-2: var(--blue-2);
    --accent-3: var(--blue-3);
    --accent-4: var(--blue-4);
    --accent-5: var(--blue-5);
    --accent-new: var(--red-2);
    --mention: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 90%) 40%, transparent);
    --mention-hover: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 95%) 40%, transparent);
    --reply: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 90%) 40%, transparent);
    --reply-hover: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 95%) 40%, transparent);

    --online: var(--green-2);
    --dnd: var(--red-2);
    --idle: var(--yellow-2);
    --streaming: var(--purple-2);
    --offline: var(--text-4);

    --border-light: var(--hover);
    --border: var(--active);
    --border-hover: var(--accent-2);
    --button-border: color-mix(in srgb, $on_surface, transparent 90%);

    --red-1: color-mix(in oklch, $error, white 15%);
    --red-2: $error;
    --red-3: $error;
    --red-4: color-mix(in oklch, $error, black 10%);
    --red-5: color-mix(in oklch, $error, black 20%);

    --green-1: oklch(from $tertiary min(calc(l + 0.08), 0.92) 0.14 145);
    --green-2: oklch(from $tertiary l 0.15 145);
    --green-3: oklch(from $tertiary l 0.15 145);
    --green-4: oklch(from $tertiary max(calc(l - 0.06), 0.05) 0.13 145);
    --green-5: oklch(from $tertiary max(calc(l - 0.12), 0.05) 0.12 145);

    --blue-1: color-mix(in oklch, $primary, white 15%);
    --blue-2: $primary;
    --blue-3: $primary;
    --blue-4: color-mix(in oklch, $primary, black 10%);
    --blue-5: color-mix(in oklch, $primary, black 20%);

    --yellow-1: oklch(from $secondary min(calc(l + 0.08), 0.92) 0.14 95);
    --yellow-2: oklch(from $secondary l 0.15 95);
    --yellow-3: oklch(from $secondary l 0.15 95);
    --yellow-4: oklch(from $secondary max(calc(l - 0.06), 0.05) 0.13 95);
    --yellow-5: oklch(from $secondary max(calc(l - 0.12), 0.05) 0.12 95);

    --purple-1: color-mix(in oklch, $on_surface_variant, white 15%);
    --purple-2: $on_surface_variant;
    --purple-3: $on_surface_variant;
    --purple-4: color-mix(in oklch, $on_surface_variant, black 10%);
    --purple-5: color-mix(in oklch, $on_surface_variant, black 20%);
}
EOF
      }

      generate_theme_css > "$out"
      generate_colors_css > "$quickcss"
    '';
  };

  generateBtopTheme = pkgs.writeShellApplication {
    name = "generate-btop-theme";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      colors="$HOME/.config/noctalia/colors.json"
      out="$HOME/.config/btop/themes/noctalia.theme"

      [ -f "$colors" ] || exit 0

      surface=$(jq -r '.mSurface' "$colors")
      surface_variant=$(jq -r '.mSurfaceVariant' "$colors")
      on_surface=$(jq -r '.mOnSurface' "$colors")
      on_surface_variant=$(jq -r '.mOnSurfaceVariant' "$colors")
      outline=$(jq -r '.mOutline' "$colors")
      primary=$(jq -r '.mPrimary' "$colors")
      secondary=$(jq -r '.mSecondary' "$colors")
      tertiary=$(jq -r '.mTertiary' "$colors")
      error=$(jq -r '.mError' "$colors")

      mkdir -p "$(dirname "$out")"

      cat > "$out" << EOF
# Noctalia btop theme - auto-generated from wallpaper colors
theme[main_bg]=$surface
theme[main_fg]=$on_surface
theme[title]=$on_surface
theme[hi_fg]=$primary
theme[selected_bg]=$surface_variant
theme[selected_fg]=$on_surface
theme[inactive_fg]=$on_surface_variant
theme[graph_text]=$on_surface
theme[meter_bg]=$outline
theme[proc_misc]=$on_surface
theme[cpu_box]=$primary
theme[mem_box]=$tertiary
theme[net_box]=$secondary
theme[proc_box]=$primary
theme[div_line]=$outline
theme[temp_start]=$tertiary
theme[temp_mid]=$on_surface_variant
theme[temp_end]=$error
theme[cpu_start]=$primary
theme[cpu_mid]=$on_surface_variant
theme[cpu_end]=$secondary
theme[free_start]=$tertiary
theme[free_mid]=
theme[free_end]=$tertiary
theme[cached_start]=$secondary
theme[cached_mid]=
theme[cached_end]=$secondary
theme[available_start]=$on_surface_variant
theme[available_mid]=$outline
theme[available_end]=$surface_variant
theme[used_start]=$error
theme[used_mid]=
theme[used_end]=$error
theme[download_start]=$secondary
theme[download_mid]=
theme[download_end]=$secondary
theme[upload_start]=$tertiary
theme[upload_mid]=
theme[upload_end]=$tertiary
theme[process_start]=$primary
theme[process_mid]=$secondary
theme[process_end]=$tertiary
EOF
    '';
  };

  generateK9sTheme = pkgs.writeShellApplication {
    name = "generate-k9s-theme";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      colors="$HOME/.config/noctalia/colors.json"
      out="$HOME/.config/k9s/skins/noctalia.yaml"

      [ -f "$colors" ] || exit 0

      surface=$(jq -r '.mSurface' "$colors")
      surface_variant=$(jq -r '.mSurfaceVariant' "$colors")
      on_surface=$(jq -r '.mOnSurface' "$colors")
      on_surface_variant=$(jq -r '.mOnSurfaceVariant' "$colors")
      primary=$(jq -r '.mPrimary' "$colors")
      secondary=$(jq -r '.mSecondary' "$colors")
      tertiary=$(jq -r '.mTertiary' "$colors")
      error=$(jq -r '.mError' "$colors")

      mkdir -p "$(dirname "$out")"

      cat > "$out" << EOF
# K9s Noctalia skin - auto-generated from wallpaper colors
foreground: &foreground "$on_surface"
background: &background "$surface"
current_line: &current_line "$surface_variant"
selection: &selection "$surface_variant"
comment: &comment "$on_surface_variant"
cyan: &cyan "$tertiary"
green: &green "$tertiary"
orange: &orange "$secondary"
magenta: &magenta "$secondary"
blue: &blue "$primary"
red: &red "$error"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *blue
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
  info:
    fgColor: *magenta
    sectionColor: *foreground
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *magenta
    buttonFocusFgColor: *background
    buttonFocusBgColor: *cyan
    labelFgColor: *orange
    fieldFgColor: *foreground
  frame:
    border:
      fgColor: *selection
      focusColor: *current_line
    menu:
      fgColor: *foreground
      keyColor: *magenta
      numKeyColor: *magenta
    crumbs:
      fgColor: *foreground
      bgColor: *current_line
      activeColor: *current_line
    status:
      newColor: *cyan
      modifyColor: *blue
      addColor: *green
      errorColor: *red
      highlightColor: *orange
      killColor: *comment
      completedColor: *comment
    title:
      fgColor: *foreground
      bgColor: *current_line
      highlightColor: *orange
      counterColor: *blue
      filterColor: *magenta
  views:
    charts:
      bgColor: default
      defaultDialColors:
        - *blue
        - *red
      defaultChartColors:
        - *blue
        - *red
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: *selection
      cursorBgColor: *current_line
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *cyan
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *blue
      showIcons: false
    yaml:
      keyColor: *magenta
      colonColor: *blue
      valueColor: *foreground
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *selection
        toggleOnColor: *magenta
        toggleOffColor: *blue
EOF
    '';
  };

  generateTmuxTheme = pkgs.writeShellApplication {
    name = "generate-tmux-theme";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      colors="$HOME/.config/noctalia/colors.json"

      [ -f "$colors" ] || exit 0
      tmux info &>/dev/null 2>&1 || exit 0

      text=$(jq -r '.mOnSurface' "$colors")
      bg_bar=$(jq -r '.mSurfaceVariant' "$colors")
      bg_pane=$(jq -r '.mSurface' "$colors")
      highlight=$(jq -r '.mPrimary' "$colors")
      selection=$(jq -r '.mSurfaceVariant' "$colors")
      info=$(jq -r '.mTertiary' "$colors")
      accent=$(jq -r '.mSecondary' "$colors")
      notice=$(jq -r '.mHover' "$colors")
      error=$(jq -r '.mError' "$colors")
      muted=$(jq -r '.mOnSurfaceVariant' "$colors")
      alert=$(jq -r '.mHover' "$colors")

      tmux set-option -gq @ukiyo-color-text "$text"
      tmux set-option -gq @ukiyo-color-bg-bar "$bg_bar"
      tmux set-option -gq @ukiyo-color-bg-pane "$bg_pane"
      tmux set-option -gq @ukiyo-color-highlight "$highlight"
      tmux set-option -gq @ukiyo-color-selection "$selection"
      tmux set-option -gq @ukiyo-color-info "$info"
      tmux set-option -gq @ukiyo-color-accent "$accent"
      tmux set-option -gq @ukiyo-color-notice "$notice"
      tmux set-option -gq @ukiyo-color-error "$error"
      tmux set-option -gq @ukiyo-color-muted "$muted"
      tmux set-option -gq @ukiyo-color-alert "$alert"

      ukiyo_root=$(tmux show-environment -g @ukiyo-root 2>/dev/null | cut -d= -f2-)
      [ -n "$ukiyo_root" ] && bash "$ukiyo_root/scripts/ukiyo.sh"
    '';
  };

  generateCiderTheme = pkgs.writeShellApplication {
    name = "generate-cider-theme";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      colors="$HOME/.config/noctalia/colors.json"
      theme_dir="$HOME/.config/sh.cider.genten/themes/kanagawa-dragon-cider"
      main_css="$theme_dir/main.css"
      out="$theme_dir/noctalia.css"
      theme_yml="$theme_dir/theme.yml"

      [ -f "$colors" ] || exit 0
      [ -f "$main_css" ] || exit 0

      surface=$(jq -r '.mSurface' "$colors")
      surface_variant=$(jq -r '.mSurfaceVariant' "$colors")
      on_surface=$(jq -r '.mOnSurface' "$colors")
      on_surface_variant=$(jq -r '.mOnSurfaceVariant' "$colors")
      outline=$(jq -r '.mOutline' "$colors")
      primary=$(jq -r '.mPrimary' "$colors")
      secondary=$(jq -r '.mSecondary' "$colors")
      tertiary=$(jq -r '.mTertiary' "$colors")
      error=$(jq -r '.mError' "$colors")

      struct_start=$(grep -n '/\* Globals \*/' "$main_css" | head -1 | cut -d: -f1)
      [ -n "$struct_start" ] || exit 1

      cat > "$out" << EOF
body.body--dark {

  --accent: $primary;
  --text: $on_surface;
  --subtext1: color-mix(in oklch, $on_surface, $surface 25%);
  --subtext0: $on_surface_variant;
  --overlay1: $error;
  --overlay0: $outline;
  --surface0: $surface_variant;
  --base: color-mix(in oklch, $surface, $surface_variant 40%);
  --mantle: color-mix(in oklch, $surface, $surface_variant 40%);
  --crust: $surface;

  --selection-bg: color-mix(in srgb, $primary, transparent 70%);
  --red: $error;
  --green: $tertiary;
  --blue: $secondary;

EOF
      tail -n +"$struct_start" "$main_css" >> "$out"

      if ! grep -q 'noctalia' "$theme_yml" 2>/dev/null; then
        cat >> "$theme_yml" << 'YAML'
  - file: noctalia.css
    name: noctalia
    description: Auto-generated theme matching current wallpaper colors
YAML
      fi
    '';
  };

  wallpaperHook = pkgs.writeShellScript "noctalia-wallpaper-hook" ''
    ${generateVesktopTheme}/bin/generate-vesktop-theme || true &
    ${generateCiderTheme}/bin/generate-cider-theme || true &
    ${generateTmuxTheme}/bin/generate-tmux-theme || true &
    ${generateBtopTheme}/bin/generate-btop-theme || true &
    ${generateK9sTheme}/bin/generate-k9s-theme || true &
    wait
  '';
in
{
  config = lib.mkIf config.bars.noctalia.enable {
    home.activation.unlockNoctaliaColors = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      colors="$HOME/.config/noctalia/colors.json"
      if [ -L "$colors" ]; then
        tmp=$(${pkgs.coreutils}/bin/mktemp)
        ${pkgs.coreutils}/bin/cp "$(${pkgs.coreutils}/bin/readlink "$colors")" "$tmp"
        ${pkgs.coreutils}/bin/rm "$colors"
        ${pkgs.coreutils}/bin/mv "$tmp" "$colors"
      elif [ ! -f "$colors" ]; then
        ${pkgs.coreutils}/bin/cp ${defaultNoctaliaColors} "$colors"
        ${pkgs.coreutils}/bin/chmod 644 "$colors"
      fi
    '';

    home.activation.patchNoctaliaGuiSettings = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      guiSettings="$HOME/.config/noctalia/gui-settings.json"
      if [ -f "$guiSettings" ]; then
        tmp=$(${pkgs.coreutils}/bin/mktemp)
        ${pkgs.jq}/bin/jq '.hooks.wallpaperChange = "${wallpaperHook}"' "$guiSettings" > "$tmp"
        ${pkgs.coreutils}/bin/mv "$tmp" "$guiSettings"
      fi
    '';

    home.activation.seedVesktopTheme = lib.hm.dag.entryAfter [ "unlockNoctaliaColors" ] ''
      ${generateVesktopTheme}/bin/generate-vesktop-theme || true
    '';

    home.activation.seedCiderTheme = lib.hm.dag.entryAfter [ "unlockNoctaliaColors" ] ''
      ${generateCiderTheme}/bin/generate-cider-theme || true
    '';

    home.activation.seedTmuxTheme = lib.hm.dag.entryAfter [ "unlockNoctaliaColors" ] ''
      ${generateTmuxTheme}/bin/generate-tmux-theme || true
    '';

    home.activation.seedBtopTheme = lib.hm.dag.entryAfter [ "unlockNoctaliaColors" ] ''
      ${generateBtopTheme}/bin/generate-btop-theme || true
    '';

    home.activation.seedK9sTheme = lib.hm.dag.entryAfter [ "unlockNoctaliaColors" ] ''
      ${generateK9sTheme}/bin/generate-k9s-theme || true
    '';

    home.packages = [ generateTmuxTheme generateBtopTheme generateK9sTheme ];

    stylix.targets.btop.enable = lib.mkForce false;
    stylix.targets.k9s.enable = lib.mkForce false;

    programs.btop.settings.color_theme = lib.mkForce "noctalia";
    programs.k9s.settings.k9s.ui.skin = lib.mkForce "noctalia";

    programs.noctalia-shell.settings = {
      colorSchemes = {
        darkMode = true;
        manualSunrise = "06:30";
        manualSunset = "18:30";
        matugenSchemeType = "scheme-content";
        schedulingMode = "off";
        useWallpaperColors = true;
      };
      hooks = {
        darkModeChange = "";
        enabled = true;
        performanceModeDisabled = "";
        performanceModeEnabled = "";
        screenLock = "";
        screenUnlock = "";
        wallpaperChange = "${wallpaperHook}";
      };
      templates = {
        alacritty = false;
        cava = false;
        code = false;
        discord = false;
        emacs = false;
        enableUserTemplates = false;
        foot = false;
        fuzzel = false;
        ghostty = true;
        gtk = false;
        helix = false;
        hyprland = false;
        kcolorscheme = false;
        kitty = true;
        mango = false;
        niri = false;
        pywalfox = false;
        qt = false;
        spicetify = false;
        telegram = false;
        vicinae = false;
        walker = false;
        wezterm = false;
        yazi = false;
        zed = false;
        zenBrowser = false;
      };
    };
  };
}
