{
  lib,
  pkgs,
  config,
  osConfig,
  ...
}:
let
  t = osConfig.host.themeData.base16Scheme;

  defaultNoctaliaColors = pkgs.writeText "noctalia-colors-default.json" (builtins.toJSON {
    mError = "#${t.base08}";
    mHover = "#${t.base0C}";
    mOnError = "#${t.base00}";
    mOnHover = "#${t.base00}";
    mOnPrimary = "#${t.base00}";
    mOnSecondary = "#${t.base00}";
    mOnSurface = "#${t.base05}";
    mOnSurfaceVariant = "#${t.base04}";
    mOnTertiary = "#${t.base00}";
    mOutline = "#${t.base03}";
    mPrimary = "#${t.base0D}";
    mSecondary = "#${t.base0E}";
    mShadow = "#${t.base00}";
    mSurface = "#${t.base00}";
    mSurfaceVariant = "#${t.base01}";
    mTertiary = "#${t.base0C}";
  });

  generateVesktopTheme = pkgs.writeShellApplication {
    name = "generate-vesktop-theme";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      colors="$HOME/.config/noctalia/colors.json"
      out="$HOME/.config/vesktop/themes/system24-kanagawa.theme.css"

      [ -f "$colors" ] || exit 0

      surface=$(jq -r '.mSurface' "$colors")
      surface_variant=$(jq -r '.mSurfaceVariant' "$colors")
      on_surface=$(jq -r '.mOnSurface' "$colors")
      on_surface_variant=$(jq -r '.mOnSurfaceVariant' "$colors")
      outline=$(jq -r '.mOutline' "$colors")
      primary=$(jq -r '.mPrimary' "$colors")
      secondary=$(jq -r '.mSecondary' "$colors")
      tertiary=$(jq -r '.mTertiary' "$colors")
      error=$(jq -r '.mError' "$colors")

      mkdir -p "$(dirname "$out")"

      cat > "$out" << EOF
/**
 * @name system24 (kanagawa)
 * @description system24 with wallpaper-matched matugen colors, generated by noctalia
 * @version 1.0.0
 */

@import url('https://refact0r.github.io/system24/build/system24.css');

body {
    --font: 'Maple Mono NF';
    --code-font: 'Maple Mono NF';
    font-weight: 300;
    letter-spacing: -0.05ch;
    --gap: 12px;
    --divider-thickness: 4px;
    --border-thickness: 2px;
    --border-hover-transition: 0.2s ease;
    --animations: on;
    --list-item-transition: 0.2s ease;
    --dms-icon-svg-transition: 0.4s ease;
    --top-bar-height: var(--gap);
    --top-bar-button-position: titlebar;
    --top-bar-title-position: off;
    --subtle-top-bar-title: off;
    --custom-window-controls: off;
    --window-control-size: 14px;
    --custom-dms-icon: off;
    --dms-icon-svg-url: url('''');
    --dms-icon-svg-size: 90%;
    --dms-icon-color-before: var(--icon-subtle);
    --dms-icon-color-after: var(--white);
    --custom-dms-background: off;
    --background-image: off;
    --transparency-tweaks: off;
    --remove-bg-layer: off;
    --panel-blur: off;
    --blur-amount: 12px;
    --bg-floating: var(--bg-3);
    --small-user-panel: on;
    --unrounding: on;
    --custom-spotify-bar: on;
    --ascii-titles: on;
    --ascii-loader: system24;
    --panel-labels: on;
    --label-color: var(--text-muted);
    --label-font-weight: 500;
}

:root {
    --colors: on;

    --text-0: $surface;
    --text-1: color-mix(in oklch, $on_surface, white 20%);
    --text-2: $on_surface;
    --text-3: color-mix(in oklch, $on_surface, $surface 15%);
    --text-4: $on_surface_variant;
    --text-5: $outline;

    --bg-1: color-mix(in oklch, $surface_variant, $on_surface 20%);
    --bg-2: color-mix(in oklch, $surface, $surface_variant 50%);
    --bg-3: $surface_variant;
    --bg-4: $surface;
    --hover: color-mix(in srgb, $on_surface_variant, transparent 87%);
    --active: color-mix(in srgb, $on_surface_variant, transparent 73%);
    --active-2: color-mix(in srgb, $on_surface_variant, transparent 66%);
    --message-hover: color-mix(in srgb, $on_surface, transparent 90%);

    --accent-1: var(--blue-1);
    --accent-2: var(--blue-2);
    --accent-3: var(--blue-3);
    --accent-4: var(--blue-4);
    --accent-5: var(--blue-5);
    --accent-new: var(--red-2);
    --mention: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 90%) 40%, transparent);
    --mention-hover: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 95%) 40%, transparent);
    --reply: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 90%) 40%, transparent);
    --reply-hover: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 95%) 40%, transparent);

    --online: var(--green-2);
    --dnd: var(--red-2);
    --idle: var(--yellow-2);
    --streaming: var(--purple-2);
    --offline: var(--text-4);

    --border-light: var(--hover);
    --border: var(--active);
    --border-hover: var(--accent-2);
    --button-border: color-mix(in srgb, $on_surface, transparent 90%);

    --red-1: color-mix(in oklch, $error, white 15%);
    --red-2: $error;
    --red-3: $error;
    --red-4: color-mix(in oklch, $error, black 10%);
    --red-5: color-mix(in oklch, $error, black 20%);

    --green-1: color-mix(in oklch, $tertiary, white 15%);
    --green-2: $tertiary;
    --green-3: $tertiary;
    --green-4: color-mix(in oklch, $tertiary, black 10%);
    --green-5: color-mix(in oklch, $tertiary, black 20%);

    --blue-1: color-mix(in oklch, $primary, white 15%);
    --blue-2: $primary;
    --blue-3: $primary;
    --blue-4: color-mix(in oklch, $primary, black 10%);
    --blue-5: color-mix(in oklch, $primary, black 20%);

    --yellow-1: color-mix(in oklch, $secondary, white 15%);
    --yellow-2: $secondary;
    --yellow-3: $secondary;
    --yellow-4: color-mix(in oklch, $secondary, black 10%);
    --yellow-5: color-mix(in oklch, $secondary, black 20%);

    --purple-1: color-mix(in oklch, $on_surface_variant, white 15%);
    --purple-2: $on_surface_variant;
    --purple-3: $on_surface_variant;
    --purple-4: color-mix(in oklch, $on_surface_variant, black 10%);
    --purple-5: color-mix(in oklch, $on_surface_variant, black 20%);
}
EOF
    '';
  };

  generateCiderTheme = pkgs.writeShellApplication {
    name = "generate-cider-theme";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      colors="$HOME/.config/noctalia/colors.json"
      theme_dir="$HOME/.config/sh.cider.genten/themes/kanagawa-dragon-cider"
      main_css="$theme_dir/main.css"
      out="$theme_dir/noctalia.css"
      theme_yml="$theme_dir/theme.yml"

      [ -f "$colors" ] || exit 0
      [ -f "$main_css" ] || exit 0

      surface=$(jq -r '.mSurface' "$colors")
      surface_variant=$(jq -r '.mSurfaceVariant' "$colors")
      on_surface=$(jq -r '.mOnSurface' "$colors")
      on_surface_variant=$(jq -r '.mOnSurfaceVariant' "$colors")
      outline=$(jq -r '.mOutline' "$colors")
      primary=$(jq -r '.mPrimary' "$colors")
      secondary=$(jq -r '.mSecondary' "$colors")
      tertiary=$(jq -r '.mTertiary' "$colors")
      error=$(jq -r '.mError' "$colors")

      struct_start=$(grep -n '/\* Globals \*/' "$main_css" | head -1 | cut -d: -f1)
      [ -n "$struct_start" ] || exit 1

      cat > "$out" << EOF
body.body--dark {

  --accent: $primary;
  --text: $on_surface;
  --subtext1: color-mix(in oklch, $on_surface, $surface 25%);
  --subtext0: $on_surface_variant;
  --overlay1: $error;
  --overlay0: $outline;
  --surface0: $surface_variant;
  --base: color-mix(in oklch, $surface, $surface_variant 40%);
  --mantle: color-mix(in oklch, $surface, $surface_variant 40%);
  --crust: $surface;

  --selection-bg: color-mix(in srgb, $primary, transparent 70%);
  --red: $error;
  --green: $tertiary;
  --blue: $secondary;

EOF
      tail -n +"$struct_start" "$main_css" >> "$out"

      if ! grep -q 'noctalia' "$theme_yml" 2>/dev/null; then
        cat >> "$theme_yml" << 'YAML'
  - file: noctalia.css
    name: noctalia
    description: Auto-generated theme matching current wallpaper colors
YAML
      fi
    '';
  };

  wallpaperHook = pkgs.writeShellScript "noctalia-wallpaper-hook" ''
    ${generateVesktopTheme}/bin/generate-vesktop-theme &
    ${generateCiderTheme}/bin/generate-cider-theme &
    wait
  '';
in
{
  config = lib.mkIf config.bars.noctalia.enable {
    home.activation.unlockNoctaliaColors = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      colors="$HOME/.config/noctalia/colors.json"
      if [ -L "$colors" ]; then
        tmp=$(${pkgs.coreutils}/bin/mktemp)
        ${pkgs.coreutils}/bin/cp "$(${pkgs.coreutils}/bin/readlink "$colors")" "$tmp"
        ${pkgs.coreutils}/bin/rm "$colors"
        ${pkgs.coreutils}/bin/mv "$tmp" "$colors"
      elif [ ! -f "$colors" ]; then
        ${pkgs.coreutils}/bin/cp ${defaultNoctaliaColors} "$colors"
        ${pkgs.coreutils}/bin/chmod 644 "$colors"
      fi
    '';

    home.activation.seedVesktopTheme = lib.hm.dag.entryAfter [ "unlockNoctaliaColors" ] ''
      ${generateVesktopTheme}/bin/generate-vesktop-theme || true
    '';

    home.activation.seedCiderTheme = lib.hm.dag.entryAfter [ "unlockNoctaliaColors" ] ''
      ${generateCiderTheme}/bin/generate-cider-theme || true
    '';

    programs.noctalia-shell.settings = {
      colorSchemes = {
        darkMode = true;
        manualSunrise = "06:30";
        manualSunset = "18:30";
        matugenSchemeType = "scheme-fruit-salad";
        schedulingMode = "off";
        useWallpaperColors = true;
      };
      hooks = {
        darkModeChange = "";
        enabled = true;
        performanceModeDisabled = "";
        performanceModeEnabled = "";
        screenLock = "";
        screenUnlock = "";
        wallpaperChange = "${wallpaperHook}";
      };
      templates = {
        alacritty = false;
        cava = false;
        code = false;
        discord = false;
        emacs = false;
        enableUserTemplates = false;
        foot = false;
        fuzzel = false;
        ghostty = true;
        gtk = false;
        helix = false;
        hyprland = false;
        kcolorscheme = false;
        kitty = true;
        mango = false;
        niri = false;
        pywalfox = false;
        qt = false;
        spicetify = false;
        telegram = false;
        vicinae = false;
        walker = false;
        wezterm = false;
        yazi = false;
        zed = false;
        zenBrowser = false;
      };
    };
  };
}
